"""manufacturing

Revision ID: 289291e8b5da
Revises: 860fd778d2ba
Create Date: 2026-08-07 15:12:45.547387
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '289291e8b5da'
down_revision: Union[str, None] = '860fd778d2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills_of_materials',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('output_qty', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('labour_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('overhead_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('wastage_percent', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_bom_name')
    )
    op.create_index(op.f('ix_bills_of_materials_business_id'), 'bills_of_materials', ['business_id'], unique=False)
    op.create_index(op.f('ix_bills_of_materials_client_uuid'), 'bills_of_materials', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_bills_of_materials_created_at'), 'bills_of_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_bills_of_materials_is_deleted'), 'bills_of_materials', ['is_deleted'], unique=False)
    op.create_index('ix_bom_item', 'bills_of_materials', ['business_id', 'item_id'], unique=False)
    op.create_table('bom_components',
    sa.Column('bom_id', app.core.types.GUID(), nullable=False),
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('qty', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'item_id', name='uq_bom_component')
    )
    op.create_index(op.f('ix_bom_components_bom_id'), 'bom_components', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_components_business_id'), 'bom_components', ['business_id'], unique=False)
    op.create_index(op.f('ix_bom_components_client_uuid'), 'bom_components', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_bom_components_created_at'), 'bom_components', ['created_at'], unique=False)
    op.create_index(op.f('ix_bom_components_item_id'), 'bom_components', ['item_id'], unique=False)
    op.create_table('production_runs',
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('bom_id', app.core.types.GUID(), nullable=True),
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('item_name', sa.String(length=240), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('qty', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('material_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('labour_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('overhead_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('wastage_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('godown_id', app.core.types.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number', name='uq_production_number')
    )
    op.create_index('ix_production_date', 'production_runs', ['business_id', 'run_date'], unique=False)
    op.create_index(op.f('ix_production_runs_business_id'), 'production_runs', ['business_id'], unique=False)
    op.create_index(op.f('ix_production_runs_client_uuid'), 'production_runs', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_production_runs_created_at'), 'production_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_production_runs_is_deleted'), 'production_runs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_production_runs_item_id'), 'production_runs', ['item_id'], unique=False)
    op.create_index(op.f('ix_production_runs_run_date'), 'production_runs', ['run_date'], unique=False)
    op.create_table('consumed_materials',
    sa.Column('run_id', app.core.types.GUID(), nullable=False),
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('item_name', sa.String(length=240), nullable=False),
    sa.Column('qty', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('rate', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('value', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['production_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumed_materials_business_id'), 'consumed_materials', ['business_id'], unique=False)
    op.create_index(op.f('ix_consumed_materials_created_at'), 'consumed_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_consumed_materials_run_id'), 'consumed_materials', ['run_id'], unique=False)
    op.create_index('ix_consumed_run', 'consumed_materials', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consumed_run', table_name='consumed_materials')
    op.drop_index(op.f('ix_consumed_materials_run_id'), table_name='consumed_materials')
    op.drop_index(op.f('ix_consumed_materials_created_at'), table_name='consumed_materials')
    op.drop_index(op.f('ix_consumed_materials_business_id'), table_name='consumed_materials')
    op.drop_table('consumed_materials')
    op.drop_index(op.f('ix_production_runs_run_date'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_item_id'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_is_deleted'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_created_at'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_client_uuid'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_business_id'), table_name='production_runs')
    op.drop_index('ix_production_date', table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_index(op.f('ix_bom_components_item_id'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_created_at'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_client_uuid'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_business_id'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_bom_id'), table_name='bom_components')
    op.drop_table('bom_components')
    op.drop_index('ix_bom_item', table_name='bills_of_materials')
    op.drop_index(op.f('ix_bills_of_materials_is_deleted'), table_name='bills_of_materials')
    op.drop_index(op.f('ix_bills_of_materials_created_at'), table_name='bills_of_materials')
    op.drop_index(op.f('ix_bills_of_materials_client_uuid'), table_name='bills_of_materials')
    op.drop_index(op.f('ix_bills_of_materials_business_id'), table_name='bills_of_materials')
    op.drop_table('bills_of_materials')
    # ### end Alembic commands ###
