"""ocr jobs no longer require a stored image

Revision ID: 40b2d6fac650
Revises: dd4c6232c9b7
Create Date: 2026-07-29 11:07:37.023677
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '40b2d6fac650'
down_revision: Union[str, None] = 'dd4c6232c9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocr_jobs', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocr_jobs', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
