"""stock locations, batches, serials, transfers and loans

Revision ID: 5b5bec5690d0
Revises: 40b2d6fac650
Create Date: 2026-08-07 02:11:47.778814
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '5b5bec5690d0'
down_revision: Union[str, None] = '40b2d6fac650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transfers',
    sa.Column('from_account_id', app.core.types.GUID(), nullable=False),
    sa.Column('to_account_id', app.core.types.GUID(), nullable=False),
    sa.Column('amount', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('charges', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_uuid', name='uq_transfer_client_uuid')
    )
    op.create_index(op.f('ix_account_transfers_business_id'), 'account_transfers', ['business_id'], unique=False)
    op.create_index(op.f('ix_account_transfers_client_uuid'), 'account_transfers', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_account_transfers_created_at'), 'account_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_transfers_from_account_id'), 'account_transfers', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_account_transfers_is_deleted'), 'account_transfers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_account_transfers_to_account_id'), 'account_transfers', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_account_transfers_transfer_date'), 'account_transfers', ['transfer_date'], unique=False)
    op.create_index('ix_transfers_biz_date', 'account_transfers', ['business_id', 'transfer_date'], unique=False)
    op.create_table('loans',
    sa.Column('lender_name', sa.String(length=200), nullable=False),
    sa.Column('loan_type', sa.String(length=16), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('principal', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('interest_rate', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('interest_type', sa.String(length=16), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('emi_amount', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('account_id', app.core.types.GUID(), nullable=True),
    sa.Column('outstanding_principal', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('principal_paid', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('interest_paid', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('instalments_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_uuid', name='uq_loan_client_uuid')
    )
    op.create_index('ix_loans_biz_status', 'loans', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_loans_business_id'), 'loans', ['business_id'], unique=False)
    op.create_index(op.f('ix_loans_client_uuid'), 'loans', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_loans_created_at'), 'loans', ['created_at'], unique=False)
    op.create_index(op.f('ix_loans_is_deleted'), 'loans', ['is_deleted'], unique=False)
    op.create_table('godown_stocks',
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('godown_id', app.core.types.GUID(), nullable=False),
    sa.Column('qty', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'item_id', 'godown_id', name='uq_godown_stock')
    )
    op.create_index('ix_godown_stock_godown', 'godown_stocks', ['business_id', 'godown_id'], unique=False)
    op.create_index(op.f('ix_godown_stocks_business_id'), 'godown_stocks', ['business_id'], unique=False)
    op.create_index(op.f('ix_godown_stocks_client_uuid'), 'godown_stocks', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_godown_stocks_created_at'), 'godown_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_godown_stocks_item_id'), 'godown_stocks', ['item_id'], unique=False)
    op.create_table('loan_payments',
    sa.Column('loan_id', app.core.types.GUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('principal_component', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('interest_component', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('instalment_number', sa.Integer(), nullable=True),
    sa.Column('account_id', app.core.types.GUID(), nullable=True),
    sa.Column('expense_id', app.core.types.GUID(), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_payments_business_id'), 'loan_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_loan_payments_client_uuid'), 'loan_payments', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_loan_payments_created_at'), 'loan_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_loan_payments_is_deleted'), 'loan_payments', ['is_deleted'], unique=False)
    op.create_index('ix_loan_payments_loan_date', 'loan_payments', ['loan_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_loan_payments_loan_id'), 'loan_payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_payments_payment_date'), 'loan_payments', ['payment_date'], unique=False)
    op.create_table('item_serials',
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('batch_id', app.core.types.GUID(), nullable=True),
    sa.Column('godown_id', app.core.types.GUID(), nullable=True),
    sa.Column('purchase_voucher_id', app.core.types.GUID(), nullable=True),
    sa.Column('sale_voucher_id', app.core.types.GUID(), nullable=True),
    sa.Column('purchase_price', app.core.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('sale_price', app.core.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('sold_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['item_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'serial_number', name='uq_item_serial')
    )
    op.create_index(op.f('ix_item_serials_business_id'), 'item_serials', ['business_id'], unique=False)
    op.create_index(op.f('ix_item_serials_client_uuid'), 'item_serials', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_item_serials_created_at'), 'item_serials', ['created_at'], unique=False)
    op.create_index(op.f('ix_item_serials_is_deleted'), 'item_serials', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_item_serials_item_id'), 'item_serials', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_serials_status'), 'item_serials', ['status'], unique=False)
    op.create_index('ix_serials_item_status', 'item_serials', ['business_id', 'item_id', 'status'], unique=False)
    op.drop_constraint('uq_payment_number', 'payments', type_='unique')
    op.create_unique_constraint('uq_payment_number', 'payments', ['business_id', 'direction', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_number', 'payments', type_='unique')
    op.create_unique_constraint('uq_payment_number', 'payments', ['business_id', 'number'])
    op.drop_index('ix_serials_item_status', table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_status'), table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_item_id'), table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_is_deleted'), table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_created_at'), table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_client_uuid'), table_name='item_serials')
    op.drop_index(op.f('ix_item_serials_business_id'), table_name='item_serials')
    op.drop_table('item_serials')
    op.drop_index(op.f('ix_loan_payments_payment_date'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_loan_id'), table_name='loan_payments')
    op.drop_index('ix_loan_payments_loan_date', table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_is_deleted'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_created_at'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_client_uuid'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_business_id'), table_name='loan_payments')
    op.drop_table('loan_payments')
    op.drop_index(op.f('ix_godown_stocks_item_id'), table_name='godown_stocks')
    op.drop_index(op.f('ix_godown_stocks_created_at'), table_name='godown_stocks')
    op.drop_index(op.f('ix_godown_stocks_client_uuid'), table_name='godown_stocks')
    op.drop_index(op.f('ix_godown_stocks_business_id'), table_name='godown_stocks')
    op.drop_index('ix_godown_stock_godown', table_name='godown_stocks')
    op.drop_table('godown_stocks')
    op.drop_index(op.f('ix_loans_is_deleted'), table_name='loans')
    op.drop_index(op.f('ix_loans_created_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_client_uuid'), table_name='loans')
    op.drop_index(op.f('ix_loans_business_id'), table_name='loans')
    op.drop_index('ix_loans_biz_status', table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_transfers_biz_date', table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_transfer_date'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_to_account_id'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_is_deleted'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_from_account_id'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_created_at'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_client_uuid'), table_name='account_transfers')
    op.drop_index(op.f('ix_account_transfers_business_id'), table_name='account_transfers')
    op.drop_table('account_transfers')
    # ### end Alembic commands ###
