"""price lists and discount schemes

Revision ID: 64b0c42f246f
Revises: 5b5bec5690d0
Create Date: 2026-08-07 13:43:57.211426
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '64b0c42f246f'
down_revision: Union[str, None] = '5b5bec5690d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('adjust_percent', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('base_price', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_uuid', name='uq_price_list_client_uuid'),
    sa.UniqueConstraint('business_id', 'name', name='uq_price_list_name')
    )
    op.create_index(op.f('ix_price_lists_business_id'), 'price_lists', ['business_id'], unique=False)
    op.create_index(op.f('ix_price_lists_client_uuid'), 'price_lists', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_price_lists_created_at'), 'price_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_lists_is_deleted'), 'price_lists', ['is_deleted'], unique=False)
    op.create_table('discount_schemes',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('item_id', app.core.types.GUID(), nullable=True),
    sa.Column('category_id', app.core.types.GUID(), nullable=True),
    sa.Column('party_id', app.core.types.GUID(), nullable=True),
    sa.Column('price_list_id', app.core.types.GUID(), nullable=True),
    sa.Column('min_amount', app.core.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('min_qty', app.core.types.Quantity(precision=18, scale=4), nullable=True),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('max_discount', app.core.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_discount_scheme_name')
    )
    op.create_index(op.f('ix_discount_schemes_business_id'), 'discount_schemes', ['business_id'], unique=False)
    op.create_index(op.f('ix_discount_schemes_client_uuid'), 'discount_schemes', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_discount_schemes_created_at'), 'discount_schemes', ['created_at'], unique=False)
    op.create_index(op.f('ix_discount_schemes_is_deleted'), 'discount_schemes', ['is_deleted'], unique=False)
    op.create_index('ix_schemes_active', 'discount_schemes', ['business_id', 'is_active'], unique=False)
    op.create_table('price_list_entries',
    sa.Column('price_list_id', app.core.types.GUID(), nullable=False),
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('price', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('min_qty', app.core.types.Quantity(precision=18, scale=4), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'price_list_id', 'item_id', name='uq_price_list_item')
    )
    op.create_index('ix_price_entries_list', 'price_list_entries', ['business_id', 'price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_entries_business_id'), 'price_list_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_price_list_entries_client_uuid'), 'price_list_entries', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_price_list_entries_created_at'), 'price_list_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_list_entries_item_id'), 'price_list_entries', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_list_entries_price_list_id'), 'price_list_entries', ['price_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_list_entries_price_list_id'), table_name='price_list_entries')
    op.drop_index(op.f('ix_price_list_entries_item_id'), table_name='price_list_entries')
    op.drop_index(op.f('ix_price_list_entries_created_at'), table_name='price_list_entries')
    op.drop_index(op.f('ix_price_list_entries_client_uuid'), table_name='price_list_entries')
    op.drop_index(op.f('ix_price_list_entries_business_id'), table_name='price_list_entries')
    op.drop_index('ix_price_entries_list', table_name='price_list_entries')
    op.drop_table('price_list_entries')
    op.drop_index('ix_schemes_active', table_name='discount_schemes')
    op.drop_index(op.f('ix_discount_schemes_is_deleted'), table_name='discount_schemes')
    op.drop_index(op.f('ix_discount_schemes_created_at'), table_name='discount_schemes')
    op.drop_index(op.f('ix_discount_schemes_client_uuid'), table_name='discount_schemes')
    op.drop_index(op.f('ix_discount_schemes_business_id'), table_name='discount_schemes')
    op.drop_table('discount_schemes')
    op.drop_index(op.f('ix_price_lists_is_deleted'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_created_at'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_client_uuid'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_business_id'), table_name='price_lists')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
