"""pakistani sales tax

Revision ID: 65a055b2caf6
Revises: 289291e8b5da
Create Date: 2026-08-07 15:38:23.594208
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '65a055b2caf6'
down_revision: Union[str, None] = '289291e8b5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Every new NOT NULL column carries a server_default.
    #
    # Autogenerate does not add one, because the model's `default=` is applied
    # in Python when a row is built — which says nothing about the rows already
    # in the table. Postgres refuses to add a NOT NULL column to a table with
    # rows unless it is told what those rows should hold, so without these the
    # migration passes on an empty test database and fails on the live one.
    #
    # The defaults matter as much as their presence: fbr_enabled is false, so
    # every shop already using the app carries on billing exactly as before and
    # nobody wakes up charging their customers three percent more.
    op.add_column('business_settings', sa.Column(
        'fbr_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('business_settings', sa.Column(
        'sales_tax_rate', app.core.types.Money(precision=18, scale=4),
        nullable=False, server_default='18'))
    op.add_column('business_settings', sa.Column(
        'further_tax_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('business_settings', sa.Column(
        'further_tax_rate', app.core.types.Money(precision=18, scale=4),
        nullable=False, server_default='3'))
    op.add_column('business_settings', sa.Column(
        'withholding_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('business_settings', sa.Column(
        'withholding_rate', app.core.types.Money(precision=18, scale=4),
        nullable=False, server_default='0'))
    op.add_column('business_settings', sa.Column(
        'province', sa.String(length=24), nullable=True))

    op.add_column('parties', sa.Column('strn', sa.String(length=24), nullable=True))

    # Bills raised before this existed carried no further tax, and saying so
    # is the only honest value: they were not under-charged, the tax did not
    # apply to them.
    op.add_column('vouchers', sa.Column(
        'further_tax_amount', app.core.types.Money(precision=18, scale=4),
        nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'further_tax_amount')
    op.drop_column('parties', 'strn')
    op.drop_column('business_settings', 'province')
    op.drop_column('business_settings', 'withholding_rate')
    op.drop_column('business_settings', 'withholding_enabled')
    op.drop_column('business_settings', 'further_tax_rate')
    op.drop_column('business_settings', 'further_tax_enabled')
    op.drop_column('business_settings', 'sales_tax_rate')
    op.drop_column('business_settings', 'fbr_enabled')
    # ### end Alembic commands ###
