"""loyalty points

Revision ID: 860fd778d2ba
Revises: e337944df7ab
Create Date: 2026-08-07 14:55:14.709283
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = '860fd778d2ba'
down_revision: Union[str, None] = 'e337944df7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_programs',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('earn_rate', app.core.types.Quantity(precision=18, scale=4), nullable=False),
    sa.Column('point_value', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('min_bill_to_earn', app.core.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('min_points_to_redeem', sa.Integer(), nullable=False),
    sa.Column('max_redeem_percent', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('expires_after_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_loyalty_program_business')
    )
    op.create_index(op.f('ix_loyalty_programs_business_id'), 'loyalty_programs', ['business_id'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_client_uuid'), 'loyalty_programs', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_created_at'), 'loyalty_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_is_deleted'), 'loyalty_programs', ['is_deleted'], unique=False)
    op.create_table('loyalty_entries',
    sa.Column('party_id', app.core.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('value', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('voucher_id', app.core.types.GUID(), nullable=True),
    sa.Column('voucher_number', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('expired_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_entries_business_id'), 'loyalty_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_loyalty_entries_client_uuid'), 'loyalty_entries', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_loyalty_entries_created_at'), 'loyalty_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_entries_kind'), 'loyalty_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_loyalty_entries_party_id'), 'loyalty_entries', ['party_id'], unique=False)
    op.create_index(op.f('ix_loyalty_entries_voucher_id'), 'loyalty_entries', ['voucher_id'], unique=False)
    op.create_index('ix_loyalty_expiry', 'loyalty_entries', ['business_id', 'expires_on'], unique=False)
    op.create_index('ix_loyalty_party_date', 'loyalty_entries', ['business_id', 'party_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loyalty_party_date', table_name='loyalty_entries')
    op.drop_index('ix_loyalty_expiry', table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_voucher_id'), table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_party_id'), table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_kind'), table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_created_at'), table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_client_uuid'), table_name='loyalty_entries')
    op.drop_index(op.f('ix_loyalty_entries_business_id'), table_name='loyalty_entries')
    op.drop_table('loyalty_entries')
    op.drop_index(op.f('ix_loyalty_programs_is_deleted'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_created_at'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_client_uuid'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_business_id'), table_name='loyalty_programs')
    op.drop_table('loyalty_programs')
    # ### end Alembic commands ###
