"""recurring invoices

Revision ID: e337944df7ab
Revises: 64b0c42f246f
Create Date: 2026-08-07 14:11:34.679888
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the project's portable column types (GUID, Money, JSONType,
# TZDateTime) fully qualified, so this import has to be present.
import app.core.types


revision: str = 'e337944df7ab'
down_revision: Union[str, None] = '64b0c42f246f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_invoices',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('voucher_type', sa.String(length=24), nullable=False),
    sa.Column('party_id', app.core.types.GUID(), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('lines', app.core.types.JSONType(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('next_run_on', sa.Date(), nullable=False),
    sa.Column('last_run_on', sa.Date(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('auto_create', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_voucher_id', app.core.types.GUID(), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('last_checked_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('total_billed', app.core.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('business_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.core.types.GUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.core.types.GUID(), nullable=True),
    sa.Column('updated_by', app.core.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_due', 'recurring_invoices', ['business_id', 'is_active', 'next_run_on'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_business_id'), 'recurring_invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_client_uuid'), 'recurring_invoices', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_created_at'), 'recurring_invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_is_deleted'), 'recurring_invoices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_next_run_on'), 'recurring_invoices', ['next_run_on'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_party_id'), 'recurring_invoices', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_invoices_party_id'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_next_run_on'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_is_deleted'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_created_at'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_client_uuid'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_business_id'), table_name='recurring_invoices')
    op.drop_index('ix_recurring_due', table_name='recurring_invoices')
    op.drop_table('recurring_invoices')
    # ### end Alembic commands ###
